---
- name: Include variables
  include_vars:
    file: ../../vars.yml

- name: Install filebeat
  yum: 
    name: filebeat
    state: latest 
    update_cache: yes

- name: Create filebeat config
  template:
    src: filebeat.config.j2
    dest: "{{ filebeat_yml }}"
  notify: Restart filebeat

- name: Force systemd to reread configs
  systemd: daemon_reload=yes

- name: Enable filebeat.service
  service:
    name: filebeat.service
    state: started
    enabled: yes

