---
- name: RedHat | include variables
  include_vars:
    file: ../../vars.yml

- name: RedHat | Install filebeat
  yum: 
    name: filebeat
    state: latest 
    update_cache: yes

- name: RedHat | Create filebeat config
  template:
    src: filebeat.config.j2
    dest: "{{ filebeat_yml }}"
  notify: Restart filebeat

- name: RedHat | Enable system module
  command: filebeat modules enable system

#- name: RedHat | Setup filebeat
#  command: filebeat setup

#- name: RedHat | Setup filebeat
#  command: filebeat setup --pipelines --modules system

- name: RedHat | Force systemd to reread configs
  systemd: daemon_reload=yes

- name: RedHat | Enable filebeat.service
  service:
    name: filebeat.service
    state: started
    enabled: yes

