---

- name: Windows | Include variables
  include_vars:
    file: ../../vars.yml

- name: Windows | Create directory
  win_file:
    path: "{{ filebeat_path }}"
    state: directory

- name: Windows | Get filebeat zip
  win_get_url:
    url: "{{ filebeat_download_url_base }}/{{ filebeat_download_file }}{{ file_ext }}"
    dest: "{{ filebeat_path }}/{{ filebeat_download_file }}{{ file_ext }}"

#- name: Windows | Unzip filebeat
#  win_unzip:
#   src: "{{ filebeat_path }}/{{ filebeat_download_file }}{{ file_ext }}"
#    dest: "{{ filebeat_path }}"

- name: Windows | Install the service via script
  win_command: powershell.exe -ExecutionPolicy ByPass -File "{{ filebeat_path }}/{{ filebeat_download_file }}/install-service-filebeat.ps1"
  args:
    chdir: "{{ filebeat_path }}/{{ filebeat_download_file }}"

- name: Windows | Copy Filebeat configuration
  win_template:
    src: filebeatwin.conf.j2
    dest: "{{ filebeat_path }}/{{ filebeat_download_file }}/filebeat.yml"
  notify: Restart filebeat win

#- name: Windows | Enable and configure iis module
#  win_command: powershell.exe -cd "{{ filebeat_path }}/{{ filebeat_download_file }}" ; ./filebeat modules enable iis
#  args:
#    chdir: "{{ filebeat_path }}/{{ filebeat_download_file }}"

#- name: Windows | Copy IIS module configuration
#  win_template:
#    src: iis.yml.j2
#    dest: "{{ filebeat_path }}/{{ filebeat_download_file }}/modules.d/iis.yml"
#  notify: Restart filebeat win

- name: Windows | Enable and configure syslog system module
  win_command: powershell.exe -cd "{{ filebeat_path }}/{{ filebeat_download_file }}" ; ./filebeat modules enable system
  args:
    chdir: "{{ filebeat_path }}/{{ filebeat_download_file }}"

- name: Windows | Copy system module configuration
  win_template:
    src: system.yml.j2
    dest: "{{ filebeat_path }}/{{ filebeat_download_file }}/modules.d/system.yml"
  notify: Restart filebeat win








#- name: Windows | Copy Filebeat configuration pipeline
#  win_template:
#    src: pipeline.yml.j2
#    dest: "{{ filebeat_path }}/{{ filebeat_download_file }}/module/iis/access/ingest/pipeline.yml"
#  notify: Restart filebeat win

#- name: Windows | Enable and configure iis module pipeline
#  win_command: powershell.exe -cd "{{ filebeat_path }}/{{ filebeat_download_file }}" ; ./filebeat setup --pipelines --modules iis
#  args:
#    chdir: "{{ filebeat_path }}/{{ filebeat_download_file }}"

