---
- name: Include variables
  include_vars:
    file: ../../vars.yml

- name: Install logstash
  yum: 
    name: logstash
    state: latest 
    update_cache: yes

- name: Create beats-input.conf
  template:
    src: beats-input.conf.j2
    dest: /etc/logstash/conf.d/beats-input.conf
  notify: Restart Logstash

#- name: Create 10-syslog-filter.conf
#  template:
#    src: 10-syslog-filter.conf.j2
#    dest: /etc/logstash/conf.d/10-syslog-filter.conf
#  notify: Restart Logstash

- name: Create elasticsearch-output.conf
  template:
    src: elasticsearch-output.conf.j2
    dest: /etc/logstash/conf.d/elasticsearch-output.conf
  notify: Restart Logstash

# - name: 
#   shell: sudo -u logstash /usr/share/logstash/bin/logstash --path.settings /etc/logstash -t
#   notify: Restart Logstash

- name: Force systemd to reread configs
  systemd: daemon_reload=yes

- name: Start and Enable Logstash
  service:
    name: logstash.service
    state: started
    enabled: yes

- name: Add logstash port to firewalld
  firewalld:
    port: 5044/tcp
    permanent: yes
    state: enabled

- name: reload  service firewalld
  systemd:
    name: firewalld
    state: reloaded
    
