---
- name: Include variables
  include_vars:
    file: ../../vars.yml

- name: Install logstash
  yum: 
    name: logstash
    state: latest 
    update_cache: yes

#- name: Install logstash output email
#  command: /usr/share/logstash/bin/logstash-plugin install logstash-output-email

- name: Create 02-beats-input.conf.j2
  template:
    src: 02-beats-input.conf.j2
    dest: /etc/logstash/conf.d/02-beats-input.conf
  notify: Restart Logstash

#- name: Create 10-syslog-filter.conf.j2
#  template:
#    src: 10-syslog-filter.conf.j2
#    dest: /etc/logstash/conf.d/10-syslog-filter.conf
#  notify: Restart Logstash

#- name: Create 11-iis-filter.conf.j2
#  template:
#    src: 11-iis-filter.conf.j2
#    dest: /etc/logstash/conf.d/11-iis-filter.conf
#  notify: Restart Logstash

- name: Create 12-iis-filter.conf.j2
  template:
    src: 12-iis-filter.conf.j2
    dest: /etc/logstash/conf.d/12-iis-filter.conf
  notify: Restart Logstash

- name: Create 13-vcs-filter.conf.j2
  template:
    src: 13-vcs-filter.conf.j2
    dest: /etc/logstash/conf.d/13-vcs-filter.conf
  notify: Restart Logstash

- name: Create 30-elasticsearch-output.conf.j2
  template:
    src: 30-elasticsearch-output.conf.j2
    dest: /etc/logstash/conf.d/30-elasticsearch-output.conf
  notify: Restart Logstash


#- name: Create beats-input.conf
#  template:
#    src: input.conf.j2
#    dest: /etc/logstash/conf.d/input.conf
#  notify: Restart Logstash
#
#- name: Create iis-logs-filter.conf
#  template:
#    src: iis_filter.conf.j2
#    dest: /etc/logstash/conf.d/iis_filter.conf
#  notify: Restart Logstash
#
#- name: Create elasticsearch-output.conf
#  template:
#    src: output.conf.j2
#    dest: /etc/logstash/conf.d/output.conf
#  notify: Restart Logstash

#- name: Create my-pipeline.conf
#  template:
#    src: my-pipeline.conf.j2
#    dest: /etc/logstash/conf.d/my-pipeline.conf
#  notify: Restart Logstash

#- name: Run logstash
#  command: /usr/share/logstash/bin/logstash -f my-pipeline.conf --config.reload.automatic

# - name: 
#   shell: sudo -u logstash /usr/share/logstash/bin/logstash --path.settings /etc/logstash -t
#   notify: Restart Logstash

- name: Force systemd to reread configs
  systemd: daemon_reload=yes

- name: Start and Enable Logstash
  service:
    name: logstash.service
    state: started
    enabled: yes

- name: Add logstash port to firewalld
  firewalld:
    port: 5044/tcp
    permanent: yes
    state: enabled

- name: reload  service firewalld
  systemd:
    name: firewalld
    state: reloaded
    
