---
- name: Include variables
  include_vars:
    file: ../../vars.yml

- name: Install elasticsearch
  yum: 
    name: elasticsearch
    state: latest 
    update_cache: yes

- name: Create elasticsearch config
  template:
    src: elasticsearch.config.j2
    dest: "{{ elastic_yml }}"
  notify: Restart elasticsearch

- name: Force systemd to reread configs
  systemd: daemon_reload=yes

- name: Start elasticsearch.service
  service:
    name: elasticsearch.service
    state: started
    enabled: yes

- name: Add elasticsearch port to firewalld
  firewalld:
    port: 9200/tcp
    permanent: yes
    state: enabled

- name: reload  service firewalld
  systemd:
    name: firewalld
    state: reloaded

